#!/bin/sh

# Integration tests for shtracer
# Tests end-to-end functionality with real configuration and data

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
SHTRACER_BIN="${SCRIPT_DIR}/../../shtracer"
SHTRACER_VIEWER="${SCRIPT_DIR}/../main/shtracer_viewer.sh"
TEST_DATA_DIR="${SCRIPT_DIR}/testdata/integration"
ANSWER_DIR="${SCRIPT_DIR}/testdata/answer/integration"

##
# @brief
#
oneTimeSetUp() {
	echo "----------------------------------------"
	echo " INTEGRATION TEST : $0"
	echo "----------------------------------------"
}

##
# @brief  SetUp function for each test
#
setUp() {
	set +u
	cd "${TEST_DATA_DIR}" || exit 1
	# Clean up any previous output
	rm -rf output/
}

##
# @brief TearDown function for each test
#
tearDown() {
	# Clean up output after each test
	rm -rf "${TEST_DATA_DIR}/output/"
}

##
# @brief  Integration test for normal mode
# @tag    @IT1.1@ (FROM: @UT1.18@)
test_integration_normal_mode() {
	(
		# Arrange ---------
		cd "${TEST_DATA_DIR}" || exit 1

		# Act -------------
		"${SHTRACER_BIN}" ./config_integration.md >/dev/null 2>&1
		_EXIT_CODE=$?

		# Assert ----------
		assertEquals "Shtracer should exit successfully" 0 "${_EXIT_CODE}"

		# Check output files exist
		assertTrue "Config table should exist" "[ -f output/config/01_config_table ]"
		assertTrue "Tags file should exist" "[ -f output/tags/01_tags ]"
		assertTrue "Tag table should exist" "[ -f output/tags/04_tag_table ]"
		assertTrue "JSON output should exist" "[ -f output/output.json ]"
		assertTrue "HTML should not be generated by backend" "[ ! -f output/output.html ]"

		# Verify tag table content
		_TAG_TABLE=$(cat output/tags/04_tag_table)
		_EXPECTED=$(cat "${ANSWER_DIR}/tag_table_expected.txt")

		assertEquals "Tag table should match expected output" "${_EXPECTED}" "${_TAG_TABLE}"

		# Generate HTML via viewer (stdin JSON -> stdout HTML)
		cat output/output.json | "${SHTRACER_VIEWER}" > output/output.html
		assertEquals "Viewer should exit successfully" 0 $?
		assertTrue "HTML output should exist" "[ -f output/output.html ]"

		# Check HTML is valid (contains basic structure)
		grep -q "<!DOCTYPE html>" output/output.html
		assertEquals "HTML should have DOCTYPE" 0 $?

		grep -q "<table" output/output.html
		assertEquals "HTML should contain table" 0 $?

		# Check D3.js and Sankey elements
		grep -q "d3js.org" output/output.html
		assertEquals "HTML should include D3.js" 0 $?

		grep -q "sankey-diagram" output/output.html
		assertEquals "HTML should contain Sankey diagram container" 0 $?

		# Single-file: assets should be inlined
		grep -q "const files =" output/output.html
		assertEquals "HTML should inline show_text.js data" 0 $?
		grep -q "traceabilityData" output/output.html
		assertEquals "HTML should include embedded JSON" 0 $?

		# Check JSON is valid
		if command -v python3 >/dev/null 2>&1; then
			python3 -m json.tool output/output.json >/dev/null 2>&1
			assertEquals "JSON should be valid" 0 $?
		else
			# Fallback: basic structure checks (not a full JSON validation)
			grep -q '"metadata"' output/output.json
			assertEquals "JSON should contain metadata" 0 $?
			grep -q '"nodes"' output/output.json
			assertEquals "JSON should contain nodes" 0 $?
			grep -q '"links"' output/output.json
			assertEquals "JSON should contain links" 0 $?
			grep -q '"chains"' output/output.json
			assertEquals "JSON should contain chains" 0 $?
		fi
	)
}

##
# @brief  Integration test for --html (stdout HTML)
# @tag    @IT1.1a@ (FROM: @UT1.18@)
test_integration_html_option() {
	(
		# Arrange ---------
		cd "${TEST_DATA_DIR}" || exit 1
		rm -rf output
		mkdir -p output

		# Act -------------
		"${SHTRACER_BIN}" ./config_integration.md --html > output/output.html 2>/dev/null
		_EXIT_CODE=$?

		# Assert ----------
		assertEquals "Shtracer --html should exit successfully" 0 "${_EXIT_CODE}"
		assertTrue "JSON output should exist" "[ -f output/output.json ]"
		assertTrue "HTML output should exist" "[ -f output/output.html ]"
		grep -q "<!DOCTYPE html>" output/output.html
		assertEquals "HTML should have DOCTYPE" 0 $?
		grep -q "traceabilityData" output/output.html
		assertEquals "HTML should include embedded JSON" 0 $?
	)
}

##
# @brief  Integration test for verify mode
# @tag    @IT1.2@ (FROM: @UT1.18@)
test_integration_verify_mode() {
	(
		# Arrange ---------
		cd "${TEST_DATA_DIR}" || exit 1

		# Act -------------
		_OUTPUT=$("${SHTRACER_BIN}" ./config_integration.md -v 2>&1)
		_EXIT_CODE=$?

		# Assert ----------
		assertEquals "Verify mode should exit successfully with valid data" 0 "${_EXIT_CODE}"

		# HTML should NOT be generated in verify mode
		assertFalse "HTML should not exist in verify mode" "[ -f output/output.html ]"

		# Tag table should still be generated
		assertTrue "Tag table should exist in verify mode" "[ -f output/tags/04_tag_table ]"

		# Output should not contain pre-extra-script or post-extra-script messages
		echo "${_OUTPUT}" | grep -q "pre-extra-script"
		assertNotEquals "Output should not contain pre-extra-script in verify mode" 0 $?

		echo "${_OUTPUT}" | grep -q "post-extra-script"
		assertNotEquals "Output should not contain post-extra-script in verify mode" 0 $?
	)
}

##
# @brief  Integration test for change mode
# @tag    @IT1.3@ (FROM: @UT1.18@)
test_integration_change_mode() {
	(
		# Arrange ---------
		cd "${TEST_DATA_DIR}" || exit 1

		# Create a temporary copy of the test file
		cp req_sample.md req_sample_temp.md

		# Act -------------
		# Create a simple config that points to the temp file
		cat >config_temp.md <<'EOF'
# Temp Config

## Requirements

* **PATH**: "./req_sample_temp.md"
  * **BRIEF**: "Temporary requirements"
  * **TAG FORMAT**: `@REQ[0-9\.]+@`
  * **TAG LINE FORMAT**: `<!--.*-->`
  * **TAG-TITLE OFFSET**: 1
EOF

		"${SHTRACER_BIN}" ./config_temp.md -c "@REQ1.1@" "@REQ2.1@" >/dev/null 2>&1
		_EXIT_CODE=$?

		# Assert ----------
		assertEquals "Change mode should exit successfully" 0 "${_EXIT_CODE}"

		# Check that the tag was changed
		grep -q "@REQ2.1@" req_sample_temp.md
		assertEquals "Tag should be changed to @REQ2.1@" 0 $?

		grep -q "@REQ1.1@" req_sample_temp.md
		assertNotEquals "Original tag @REQ1.1@ should not exist" 0 $?

		# Clean up
		rm -f req_sample_temp.md config_temp.md
	)
}

##
# @brief  Integration test for multi-file traceability
# @tag    @IT1.4@ (FROM: @UT1.18@)
test_integration_multiple_files() {
	(
		# Arrange ---------
		cd "${TEST_DATA_DIR}" || exit 1

		# Act -------------
		"${SHTRACER_BIN}" ./config_integration.md >/dev/null 2>&1
		_EXIT_CODE=$?

		# Assert ----------
		assertEquals "Multi-file test should exit successfully" 0 "${_EXIT_CODE}"

		_TAG_TABLE=$(cat output/tags/04_tag_table)

		# Verify complete traceability chains exist
		echo "${_TAG_TABLE}" | grep -q "@REQ1.1@ @ARC1.1@ @IMP1.1@"
		assertEquals "Complete chain REQ->ARC->IMP should exist for requirement 1.1" 0 $?

		echo "${_TAG_TABLE}" | grep -q "@REQ1.2@ @ARC1.2@ @IMP1.2@"
		assertEquals "Complete chain REQ->ARC->IMP should exist for requirement 1.2" 0 $?

		echo "${_TAG_TABLE}" | grep -q "@REQ1.3@ @ARC1.3@ @IMP1.3@"
		assertEquals "Complete chain REQ->ARC->IMP should exist for requirement 1.3" 0 $?

		# Count total chains
		_CHAIN_COUNT=$(echo "${_TAG_TABLE}" | wc -l)
		assertEquals "Should have exactly 3 traceability chains" 3 "${_CHAIN_COUNT}"
	)
}

##
# @brief  Integration test for error handling
# @tag    @IT1.5@ (FROM: @UT1.18@)
test_integration_error_handling() {
	(
		# Arrange ---------
		cd "${TEST_DATA_DIR}" || exit 1

		# Create config with non-existent path
		cat >config_error.md <<'EOF'
# Error Config

## NonExistent

* **PATH**: "./non_existent_file.md"
  * **BRIEF**: "This file does not exist"
  * **TAG FORMAT**: `@TEST[0-9\.]+@`
  * **TAG LINE FORMAT**: `<!--.*-->`
  * **TAG-TITLE OFFSET**: 1
EOF

		# Act -------------
		_OUTPUT=$("${SHTRACER_BIN}" ./config_error.md 2>&1)
		_EXIT_CODE=$?

		# Assert ----------
		assertNotEquals "Shtracer should exit with error for non-existent file" 0 "${_EXIT_CODE}"

		# Error message should be present
		echo "${_OUTPUT}" | grep -q "error\|Error\|No linked tags"
		assertEquals "Error message should be present" 0 $?

		# Clean up
		rm -f config_error.md
	)
}

##
# @brief  Integration test for JSON export
# @tag    @IT2.1@ (FROM: @UT1.18@)
test_integration_json_export() {
	(
		# Arrange ---------
		cd "${TEST_DATA_DIR}" || exit 1

		# Act -------------
		_OUTPUT=$("${SHTRACER_BIN}" ./config_integration.md --json 2>&1)
		_EXIT_CODE=$?

		# Assert ----------
		assertEquals "Shtracer should exit successfully with JSON export" 0 "${_EXIT_CODE}"

		# Verify JSON is output to stdout (basic structure check)
		echo "${_OUTPUT}" | grep -q '"metadata"'
		assertEquals "JSON should contain metadata" 0 $?

		echo "${_OUTPUT}" | grep -q '"nodes"'
		assertEquals "JSON should contain nodes" 0 $?

		echo "${_OUTPUT}" | grep -q '"links"'
		assertEquals "JSON should contain links" 0 $?

		echo "${_OUTPUT}" | grep -q '"chains"'
		assertEquals "JSON should contain chains" 0 $?

		# HTML should NOT be generated when --json is specified
		assertTrue "HTML should not be generated with --json" "[ ! -f output/output.html ]"
	)
}

##
# @brief  Integration test for summary export
test_integration_summary_export() {
	(
		# Arrange ---------
		cd "${TEST_DATA_DIR}" || exit 1

		# Act -------------
		_OUTPUT=$("${SHTRACER_BIN}" ./config_integration.md --summary 2>&1)
		_EXIT_CODE=$?

		# Assert ----------
		assertEquals "Shtracer should exit successfully with summary" 0 "${_EXIT_CODE}"

		# Basic format checks
		echo "${_OUTPUT}" | grep -q "^Requirement$\|^Architecture$\|^Implementation$\|^Unit test$\|^Integration test$"
		assertEquals "Summary should contain layer headers" 0 $?
		echo "${_OUTPUT}" | grep -q "^  upstream: \|^  downstream: "
		assertEquals "Summary should contain upstream/downstream lines" 0 $?
		echo "${_OUTPUT}" | grep -q "%$\|<1%"
		assertEquals "Summary should contain percentage tokens" 0 $?

		# Extra scripts should be suppressed in summary output
		echo "${_OUTPUT}" | grep -q "pre-extra-script\|post-extra-script"
		assertNotEquals "Summary should not contain extra script output" 0 $?

		# HTML/JSON should NOT be generated in summary mode
		assertTrue "HTML should not be generated with --summary" "[ ! -f output/output.html ]"
		assertTrue "JSON should not be generated with --summary" "[ ! -f output/output.json ]"
	)
}

# shellcheck source=shunit2/shunit2
. "${SCRIPT_DIR}/shunit2/shunit2"
